# Generated by Django 3.0.3 on 2020-08-02 14:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(0, 'Technical'), (1, 'Product'), (2, 'Operations'), (3, 'Design'), (4, 'Marketing')], verbose_name='Job Type')),
                ('job_name', models.CharField(max_length=250, verbose_name='Job Name')),
                ('job_city', models.SmallIntegerField(choices=[(0, 'Beijing'), (1, 'Shanghai'), (2, 'Shenzhen'), (3, 'Hangzhou'), (4, 'Guangzhou')], verbose_name='City')),
                ('job_responsibility', models.TextField(max_length=1024, verbose_name='Job Responsibility')),
                ('job_requirement', models.TextField(max_length=1024, verbose_name='Job Requirement')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Date')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
