# Generated by Django 3.1 on 2020-08-29 23:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_auto_20200828_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=135, verbose_name='Name')),
                ('city', models.CharField(blank=True, max_length=135, verbose_name='City')),
                ('phone', models.CharField(max_length=135, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=135, verbose_name='Email')),
                ('apply_position', models.CharField(blank=True, max_length=135, verbose_name='Applied Position')),
                ('born_address', models.CharField(blank=True, max_length=135, verbose_name='Hometown')),
                ('gender', models.CharField(blank=True, max_length=135, verbose_name='Gender')),
                ('candidate_introduction', models.CharField(blank=True, max_length=1024, verbose_name='Candidate Introduction')),
                ('work_experience', models.CharField(blank=True, max_length=1024, verbose_name='Work Experience')),
                ('project_experience', models.CharField(blank=True, max_length=1024, verbose_name='Project Experience')),
                ('bachelor_school', models.CharField(blank=True, max_length=135, verbose_name='Bachelor School')),
                ('master_school', models.CharField(blank=True, max_length=135, verbose_name='Master School')),
                ('doctor_school', models.CharField(blank=True, max_length=135, verbose_name='PhD School')),
                ('major', models.CharField(blank=True, max_length=135, verbose_name='Major')),
                ('degree', models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=135, verbose_name='Degree')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modified Date')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
        ),
    ]
