# Generated by Django 3.1 on 2020-10-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200830_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resume List'},
        ),
        migrations.AddField(
            model_name='resume',
            name='attachment',
            field=models.FileField(blank=True, upload_to='file/', verbose_name='Resume Attachment'),
        ),
        migrations.AddField(
            model_name='resume',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='candidate_introduction',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Self Introduction'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='city',
            field=models.CharField(max_length=135, verbose_name='City'),
        ),
    ]
