# Generated by Django 3.0.3 on 2020-08-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False, unique=True)),
                ('userid', models.IntegerField(blank=True, unique=True, verbose_name='Applicant ID')),
                ('username', models.CharField(max_length=135, verbose_name='Name')),
                ('city', models.CharField(max_length=135, verbose_name='City')),
                ('phone', models.CharField(max_length=135, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=135, verbose_name='Email')),
                ('apply_position', models.CharField(blank=True, max_length=135, verbose_name='Applied Position')),
                ('born_address', models.CharField(blank=True, max_length=135, verbose_name='Hometown')),
                ('gender', models.CharField(blank=True, max_length=135, verbose_name='Gender')),
                ('candidate_remark', models.CharField(blank=True, max_length=135, verbose_name='Candidate Remark')),
                ('bachelor_school', models.CharField(blank=True, max_length=135, verbose_name='Bachelor School')),
                ('master_school', models.CharField(blank=True, max_length=135, verbose_name='Master School')),
                ('doctor_school', models.CharField(blank=True, max_length=135, verbose_name='PhD School')),
                ('degree', models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=135, verbose_name='Degree')),
                ('major', models.CharField(blank=True, max_length=135, verbose_name='Major')),
                ('test_score_of_general_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='General Ability Test Score')),
                ('paper_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Paper Test Score')),
                ('first_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='1st Round Score')),
                ('first_learning_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Learning Ability Score')),
                ('first_professional_competency', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Professional Competency Score')),
                ('first_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Advantages')),
                ('first_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Disadvantages')),
                ('first_result', models.CharField(blank=True, choices=[('Recommend 2nd Round', 'Recommend 2nd Round'), ('Pending', 'Pending'), ('Reject', 'Reject')], max_length=256, verbose_name='1st Round Result')),
                ('first_recommend_position', models.CharField(blank=True, max_length=256, verbose_name='Recommended Department')),
                ('first_interviewer', models.CharField(blank=True, max_length=256, verbose_name='Interviewer')),
                ('first_remark', models.CharField(blank=True, max_length=135, verbose_name='1st Round Remark')),
                ('second_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='2nd Round Score')),
                ('second_learning_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Learning Ability Score')),
                ('second_professional_competency', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Professional Competency Score')),
                ('second_pursue_of_excellence', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Pursuit of Excellence Score')),
                ('second_communication_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Communication Ability Score')),
                ('second_pressure_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Stress Resistance Score')),
                ('second_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Advantages')),
                ('second_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Disadvantages')),
                ('second_result', models.CharField(blank=True, choices=[('Recommend Hire', 'Recommend Hire'), ('Pending', 'Pending'), ('Reject', 'Reject')], max_length=256, verbose_name='2nd Round Result')),
                ('second_recommend_position', models.CharField(blank=True, max_length=256, verbose_name='Recommended Department')),
                ('second_interviewer', models.CharField(blank=True, max_length=256, verbose_name='Interviewer')),
                ('second_remark', models.CharField(blank=True, max_length=135, verbose_name='2nd Round Remark')),
                ('hr_score', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Overall Grade')),
                ('hr_responsibility', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Responsibility')),
                ('hr_communication_ability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Communication')),
                ('hr_logic_ability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Logical Thinking')),
                ('hr_potential', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Potential')),
                ('hr_stability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR Stability')),
                ('hr_advantage', models.TextField(blank=True, max_length=1024, verbose_name='Advantages')),
                ('hr_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='Disadvantages')),
                ('hr_result', models.CharField(blank=True, choices=[('Recommend Hire', 'Recommend Hire'), ('Pending', 'Pending'), ('Reject', 'Reject')], max_length=256, verbose_name='HR Round Result')),
                ('hr_interviewer', models.CharField(blank=True, max_length=256, verbose_name='HR Interviewer')),
                ('hr_remark', models.CharField(blank=True, max_length=256, verbose_name='HR Round Remark')),
                ('creator', models.CharField(blank=True, max_length=256, verbose_name='Creator')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Date')),
                ('last_editor', models.CharField(blank=True, max_length=256, verbose_name='Last Editor')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidate',
                'db_table': 'candidate',
            },
        ),
    ]
